# Namespaces for yudao project
apiVersion: v1
kind: Namespace
metadata:
  name: default
  labels:
    name: default
    project: yudao
---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev
    project: yudao
    environment: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    project: yudao
    environment: production
